//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptPetProject.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AdoptPetProject.Resources.SharedResource_en_US", typeof(SharedResource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        internal static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        internal static string addlisting {
            get {
                return ResourceManager.GetString("addlisting", resourceCulture);
            }
        }
        
        internal static string adopt {
            get {
                return ResourceManager.GetString("adopt", resourceCulture);
            }
        }
        
        internal static string callus {
            get {
                return ResourceManager.GetString("callus", resourceCulture);
            }
        }
        
        internal static string adoptPet {
            get {
                return ResourceManager.GetString("adoptPet", resourceCulture);
            }
        }
        
        internal static string choosecategory {
            get {
                return ResourceManager.GetString("choosecategory", resourceCulture);
            }
        }
        
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        internal static string dailyDescription {
            get {
                return ResourceManager.GetString("dailyDescription", resourceCulture);
            }
        }
        
        internal static string dailyInfo {
            get {
                return ResourceManager.GetString("dailyInfo", resourceCulture);
            }
        }
        
        internal static string easytouse {
            get {
                return ResourceManager.GetString("easytouse", resourceCulture);
            }
        }
        
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        internal static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        internal static string fastContact {
            get {
                return ResourceManager.GetString("fastContact", resourceCulture);
            }
        }
        
        internal static string fastContactDescription {
            get {
                return ResourceManager.GetString("fastContactDescription", resourceCulture);
            }
        }
        
        internal static string fillDescription {
            get {
                return ResourceManager.GetString("fillDescription", resourceCulture);
            }
        }
        
        internal static string fillInfo {
            get {
                return ResourceManager.GetString("fillInfo", resourceCulture);
            }
        }
        
        internal static string findmate {
            get {
                return ResourceManager.GetString("findmate", resourceCulture);
            }
        }
        
        internal static string firstComment {
            get {
                return ResourceManager.GetString("firstComment", resourceCulture);
            }
        }
        
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        internal static string investor {
            get {
                return ResourceManager.GetString("investor", resourceCulture);
            }
        }
        
        internal static string keyword {
            get {
                return ResourceManager.GetString("keyword", resourceCulture);
            }
        }
        
        internal static string lastcomments {
            get {
                return ResourceManager.GetString("lastcomments", resourceCulture);
            }
        }
        
        internal static string listing {
            get {
                return ResourceManager.GetString("listing", resourceCulture);
            }
        }
        
        internal static string petlover {
            get {
                return ResourceManager.GetString("petlover", resourceCulture);
            }
        }
        
        internal static string pleasure {
            get {
                return ResourceManager.GetString("pleasure", resourceCulture);
            }
        }
        
        internal static string pleasureDescription {
            get {
                return ResourceManager.GetString("pleasureDescription", resourceCulture);
            }
        }
        
        internal static string popular {
            get {
                return ResourceManager.GetString("popular", resourceCulture);
            }
        }
        
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        internal static string secondComment {
            get {
                return ResourceManager.GetString("secondComment", resourceCulture);
            }
        }
        
        internal static string selectLang {
            get {
                return ResourceManager.GetString("selectLang", resourceCulture);
            }
        }
        
        internal static string signDescription {
            get {
                return ResourceManager.GetString("signDescription", resourceCulture);
            }
        }
        
        internal static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        internal static string sponsored {
            get {
                return ResourceManager.GetString("sponsored", resourceCulture);
            }
        }
        
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        internal static string successinfo {
            get {
                return ResourceManager.GetString("successinfo", resourceCulture);
            }
        }
        
        internal static string whatsaidcustomers {
            get {
                return ResourceManager.GetString("whatsaidcustomers", resourceCulture);
            }
        }
        
        internal static string whywe {
            get {
                return ResourceManager.GetString("whywe", resourceCulture);
            }
        }
        
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        internal static string turkish {
            get {
                return ResourceManager.GetString("turkish", resourceCulture);
            }
        }
        
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        internal static string mostLiked {
            get {
                return ResourceManager.GetString("mostLiked", resourceCulture);
            }
        }
        
        internal static string easytouseDescription {
            get {
                return ResourceManager.GetString("easytouseDescription", resourceCulture);
            }
        }
        
        internal static string addfree {
            get {
                return ResourceManager.GetString("addfree", resourceCulture);
            }
        }
        
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        internal static string rememberme {
            get {
                return ResourceManager.GetString("rememberme", resourceCulture);
            }
        }
        
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        internal static string repassword {
            get {
                return ResourceManager.GetString("repassword", resourceCulture);
            }
        }
        
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        internal static string listingtitle {
            get {
                return ResourceManager.GetString("listingtitle", resourceCulture);
            }
        }
        
        internal static string listingage {
            get {
                return ResourceManager.GetString("listingage", resourceCulture);
            }
        }
        
        internal static string listingprovince {
            get {
                return ResourceManager.GetString("listingprovince", resourceCulture);
            }
        }
        
        internal static string listingcategory {
            get {
                return ResourceManager.GetString("listingcategory", resourceCulture);
            }
        }
        
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        internal static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        internal static string maxsize {
            get {
                return ResourceManager.GetString("maxsize", resourceCulture);
            }
        }
        
        internal static string createlisting {
            get {
                return ResourceManager.GetString("createlisting", resourceCulture);
            }
        }
    }
}
